spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/erudio?useLegacyDatetimeCode=true&serverTimezone=UTC
    username: postgres
    password: 1129
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
        ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true